### ISSUE TITLE
Comment in /* ... */ is not handled

### ISSUE THREAD

**Issue by sergru** [akrylysov/intellij-nsis#1]
I use comments in block format, fir example:
```
/*
  My comments are here.
  
  $0 <- is part of comment, not variable.
  HKLM - and this one,
  $ProgramFiles <- and this
  !define NAME "Error in styling" <- this is a comment too.
  
  In multiple lines.
*/

!define NAME "This is code"  ; styled ok.
```

Plugin does not recognize comment blocks like this ```/* COMMENT */``` and treats them as regular code.

**Comment by akrylysov** [comment]
Hi! Thanks for the bug report, but unfortunately the project is no longer maintained. I haven't updated it in 7(!) years. Feel free to fork the project to fix the issue.
